server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  data:
    mongodb:
      uri:  mongodb://root:123@localhost:27017
      database: xc_media
#rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: kavito
    password: 123456
    virtual-host: /kavito
xc-service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  video-location: E:/xcEdu/xcEduUI/xuecheng/video/
  ffmpeg-path: D:/Program Files/ffmpeg/bin/ffmpeg.exe