server:
  port: 10086
spring:
  application:
    name: test-rabbitmq-demo
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: kavito
    password: 123456
    virtualHost: /kavito
    #template:
      #retry:
        #enabled: true
        #initial-interval: 10000ms
        #max-interval: 300000ms
        #multiplier: 2
      #exchange: topic.exchange
    publisher-confirms: true